# Generated by Django 3.0.2 on 2020-01-08 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Louvor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero_da_pasta', models.IntegerField(null=True)),
                ('estilo', models.CharField(choices=[('agitado', 'agitado'), ('adoracao', 'adoração'), ('agitado_adoracao', 'agitado/adoracao')], default='agitado', max_length=20)),
                ('ritmo', models.CharField(choices=[('outro', 'outro'), ('axe', 'axé'), ('eletronica', 'eletronica'), ('forro', 'forró'), ('pop', 'pop'), ('rock', 'rock'), ('samba', 'samba/pagode'), ('sertanejo', 'sertanejo')], default='outro', max_length=20)),
                ('vezes_tocada', models.IntegerField(default=0)),
                ('vezes_ensaiada', models.IntegerField(default=0)),
                ('tom', models.CharField(blank=True, max_length=10)),
                ('link_cifra', models.URLField(max_length=300)),
                ('favoritado_usuario', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('louvor', models.ManyToManyField(blank=True, to='songs.Louvor')),
            ],
        ),
    ]
