# Generated by Django 3.0.2 on 2020-01-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200108_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banda',
            options={'verbose_name_plural': 'Bandas'},
        ),
        migrations.AlterModelOptions(
            name='louvor',
            options={'verbose_name_plural': 'Louvores'},
        ),
        migrations.AlterField(
            model_name='louvor',
            name='tom',
            field=models.CharField(blank=True, default='Original', max_length=10),
        ),
    ]
