# Generated by Django 3.0.2 on 2020-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20200108_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louvor',
            name='numero_da_pasta',
            field=models.CharField(blank=True, default='sem numero', max_length=10),
        ),
    ]
