# Generated by Django 3.0.2 on 2020-01-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200108_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louvor',
            name='numero_da_pasta',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
