# Generated by Django 3.0.2 on 2020-01-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200109_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='louvor',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
