# Generated by Django 3.0.2 on 2020-01-11 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_louvor_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='louvor',
            name='banda',
        ),
        migrations.AddField(
            model_name='louvor',
            name='banda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.Banda'),
            preserve_default=False,
        ),
    ]
