# Generated by Django 3.0.2 on 2020-01-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200111_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='louvor',
            name='tem_slide',
            field=models.BooleanField(default=False),
        ),
    ]
